### ISSUE TITLE
install the dmac node

### ISSUE THREAD

**Issue by AlexanderBarbie** [okebkal/dmac#11]
We want to use the install space instead of the devel space.

Please add after

target_link_libraries(dmac
  ${catkin_LIBRARIES}
)

the following lines to the CMakesLists.txt

install(TARGETS dmac
        RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})

**Comment by okebkal** [comment]
Thanks for the pull request. It solves also this issue, right?

**Comment by AlexanderBarbie** [comment]
right
