### ISSUE TITLE
Message DMACPayload different types

### ISSUE THREAD

**Issue by ghost** [okebkal/dmac#2]
It's not a big of a problem but inside msg/DMACPayload.msg, constants are uint8 and msg_id uint32.

uint8 DMAC_BURST = 0
uint8 DMAC_IM = 1
uint8 DMAC_IMS = 2
uint8 DMAC_PBM = 3

uint32 msg_id

**Comment by okebkal** [comment]
I don't use msg_id at the moment, but the constants are connected to the type field:
uint8 type # media access type: BURST/IM/IMS/PBM

**Comment by ghost** [comment]
My mistake sorry!
