### ISSUE TITLE
Loop on /sync topic

### ISSUE THREAD

**Issue by ghost** [okebkal/dmac#4]
On ROS published topics are also received by the same node when there's a subscriber for it.

line 90 and 91 on parser.h

```
pub_sync_ = nh_.advertise<DMACSync>(config.node_name + "/sync", 100);
sub_sync_ = nh_.subscribe(config.node_name + "/sync", 100, &parser::syncCallback, this);
```

All the synchronous modem replies will be redirected again to the modem.

**Comment by okebkal** [comment]
there is a criteria to identify this particular situation in the callback:

```
        if (!msg->report.empty()) {
            /* ignore published by oursleves modem response */
            return;
        }
```

is it worth to have to different topics for in and out?

**Comment by okebkal** [comment]
But, if this is a bad practice for ROS, I will fix it...
