### ISSUE TITLE
Initializer messages

### ISSUE THREAD

**Issue by ghost** [okebkal/dmac#6]
It would be nice to have a parameter to send commands in the beginning like "resetting device", "the id of the modem" or "ask for the version to be on the logs"

yaml example:
`initialiser: ["ATZ0", "ATI0", "ATI1", "AT!AL1"]`

**Comment by okebkal** [comment]
yes, I am planning to implement it, but no time this week

**Comment by ghost** [comment]
Ok.
For now we have a bunch of rostopic pubs in a launch file that does the job.

**Comment by okebkal** [comment]
please note, the initializer has different format in my implementation:
initialiser: {"@ZU": "1", "@ZX": "1", "!C":"2"}
