### ISSUE TITLE
payload populated with 0's

### ISSUE THREAD

**Issue by ghost** [okebkal/dmac#8]
/inbox and /recv topics are being populated with 0's (null character)
If we look at the data parameter in RECVIMS (/raw topic) we see chars different from 0

The test we made involves sending binary strings maybe this is causing the problem.

**Comment by okebkal** [comment]
for the test I have sent instant message with the following payload: 0x00 0x00 0x20 0x31, on the receiving side the messages was successfully received:

```
> rostopic echo /modem1/inbox |xxd
0000000: 6865 6164 6572 3a20 0a20 2073 6571 3a20  header: .  seq: 
0000010: 330a 2020 7374 616d 703a 200a 2020 2020  3.  stamp: .    
0000020: 7365 6373 3a20 3134 3634 3636 3238 3434  secs: 1464662844
0000030: 0a20 2020 206e 7365 6373 3a20 3833 3834  .    nsecs: 8384
0000040: 3737 3436 370a 2020 6672 616d 655f 6964  77467.  frame_id
0000050: 3a20 2727 0a73 6f75 7263 653a 200a 2020  : ''.source: .  
0000060: 6e61 6d65 3a20 320a 2020 726f 6c65 3a20  name: 2.  role: 
0000070: 320a 2020 6964 3a20 320a 7061 796c 6f61  2.  id: 2.payloa
0000080: 643a 2000 0020 310a 6c65 6e67 7468 3a20  d: .. 1.length: 
```

could you give some example, when the payload is corrupted (with propagating nulls)?

**Comment by ghost** [comment]
I have attached some samples of inbox and raw topics.
I think they were all failing...

[raw.txt](https://github.com/okebkal/dmac/files/293215/raw.txt)
[inbox.txt](https://github.com/okebkal/dmac/files/293216/inbox.txt)

**Comment by okebkal** [comment]
To test the issue I have sent from one modem the same massage as you have in the raw.txt, with nulls, \r and \n, on the other side I have checked its reception with rostopic echo. It works for me.
Could you try the same test on your system?

**Comment by ghost** [comment]
I tried and it worked only on the first "RECVIMS".

Setup using the emulator:
- one dmac_driver on the receive side 
- rostopic echo /modem1/inbox | xxd     (payload variable comes with nulls after the first RECVIMS)
- python script (attached) for pinging on the sender side

[evologics_ping.zip](https://github.com/okebkal/dmac/files/295335/evologics_ping.zip)
(change the TCP_IP variable for the correct modem IP)

**Comment by okebkal** [comment]
the issue is likely caused by hardcoded mode of the modem in tcp_client.h

```
        /*parser_(dmac::DMAC_NET, config, this)*/
        parser_(dmac::DMAC_AT, config, this)
```

but you have NET filter configured on the modems. 
I didn't yet implemented mode autodetection, but it will be done soon. So far, please unquote the NET setting and quote the AT setting.

**Comment by ghost** [comment]
Maybe I am missing something...

Both emulator and our modems are NET filtered, right?

on the tcp_client.h line 56 (commit  3dbb561) you have this:

> ```
>     parser_(dmac::DMAC_NET, config, this)
> ```

There's nothing quoted...

**Comment by okebkal** [comment]
You are right, I didn't push it. 
But the problem is, that I get correct data in payload also with your script.
